<a href="https://colab.research.google.com/github/Taeseong-eom/ApplePython/blob/main/%EC%9E%91%EA%B3%A1AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import tensorflow as tf

with open('/content/drive/MyDrive/Colab Notebooks/pianoabc.txt','r') as file:
  text = file.read()
# 악보를 문자로 바꿀 수 있을까?
# abc notation 쓰면 된다.
# txt 파일은 악보를 txt로 바꿔놨다.

# 이제 문자를 숫자로 만들어서 학습시키자.
# 문자를 숫자로 바꾸는 방법
# 1. Bag of words(단어주머니) 만들어서 숫자로 변환
utext = list(set(text))
utext.sort()
# print(utext)

# 문자 -> 숫자 변환 딕셔너리
text_to_num = {}
num_to_text = {}
for i, data in enumerate(utext): # enumerate 로 변수 2개 사용
  text_to_num[data] = i
for i, data in enumerate(utext):
  num_to_text[i] = data

숫자화text=[]
for i in text:
  숫자화text.append(text_to_num[i])
# print(숫자화text)

# 그럼 이제 숫자화text를 가지고 trainX,Y를 만들어보자.

trainX, trainY = [], []

for i in range(0, len(숫자화text)-25):
    trainX.append(숫자화text[i:i+25])
    trainY.append(숫자화text[i+25])

import numpy as np
# 원핫인코딩할때 유니크한 문자가 많으면 부담된다.
# 그럴때 embedding layer를 사용한다.

# 원핫인코딩을 하자.
trainX = tf.one_hot(trainX, 31)
trainY = tf.one_hot(trainY, 31)
print(trainX[0:2])



tf.Tensor(
[[[0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]], shape=(2, 25, 31), dtype=float32)


In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(100, input_shape=(25,31)), # 노드수
    tf.keras.layers.Dense(31, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy']) # 원핫인코딩이 되어 있어서 sparse를 안붙여도 됨.
model.fit(trainX, trainY, batch_size=64, epochs=1, verbose=2) # batch_size=64 == 64번 할때마다 w 값 업데이트 // verbose=2 출력 값이 많으면 다운될 수 있어서 출력 많이 하지 말라 명령.
model.save('/content/drive/MyDrive/Colab Notebooks/model!')

4563/4563 - 170s - loss: 1.5987 - accuracy: 0.4958 - 170s/epoch - 37ms/step


In [18]:
import tensorflow as tf
import numpy as np

Pmodel = tf.keras.models.load_model('/content/drive/MyDrive/Colab Notebooks/model1')

첫입력값 = 숫자화text[117:117+25]
첫입력값 = tf.one_hot(첫입력값, 31)
첫입력값 = tf.expand_dims(첫입력값, axis=0)
print(첫입력값)
예측값 = Pmodel.predict(첫입력값)
예측값 = np.argmax(예측값[0])
print(예측값)
print(숫자화text[117+25])
print(num_to_text[예측값])

tf.Tensor(
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0.

In [36]:
music = []
for i in range(200):
  # 첫 입력값 만들기
  # 다음 값 예측
  예측값 = Pmodel.predict(첫입력값, verbose=0)
  예측값 = np.argmax(예측값[0])

  # print(예측값)

  # 예측값 [] 저장
  music.append(예측값)

  # 입력값 짜르기
  다음입력값 = 첫입력값.numpy()[0][1:]
  # print(다음입력값)

  # 새로운 입력값 만들기(+예측값)
  one_hot_num = tf.one_hot(예측값, 31)
  # print(one_hot_num)

  첫입력값 = np.vstack([다음입력값 , one_hot_num.numpy() ]) # 리스트끼리 더해줌
  첫입력값 = tf.expand_dims(첫입력값, axis=0)
  # 원핫인코딩, expand dims
print(music)

[5, 0, 20, 0, 26, 15, 3, 5, 26, 3, 5, 0, 16, 0, 27, 3, 5, 26, 3, 5, 25, 3, 5, 15, 3, 5, 0, 17, 10, 0, 14, 3, 5, 20, 3, 5, 19, 3, 5, 14, 3, 5, 0, 20, 0, 20, 3, 5, 14, 3, 5, 15, 3, 5, 25, 3, 5, 0, 17, 10, 0, 26, 3, 5, 25, 3, 5, 15, 3, 5, 14, 3, 5, 0, 20, 0, 20, 15, 3, 5, 25, 3, 5, 26, 15, 0, 17, 0, 14, 3, 5, 19, 3, 5, 20, 3, 5, 14, 3, 5, 15, 3, 5, 14, 3, 5, 20, 3, 5, 19, 3, 5, 0, 17, 0, 17, 3, 5, 18, 3, 5, 19, 3, 5, 20, 3, 5, 0, 14, 10, 0, 14, 3, 5, 15, 3, 5, 14, 3, 5, 20, 3, 5, 0, 17, 0, 19, 17, 0, 14, 10, 0, 16, 3, 5, 19, 3, 5, 18, 3, 5, 17, 3, 5, 0, 17, 0, 19, 14, 0, 20, 0, 20, 15, 3, 5, 25, 3, 5, 0, 17, 0, 26, 3, 5, 25, 3, 5, 26, 3, 5, 27, 3, 5, 0, 20, 0, 26, 15, 3]


In [37]:
music_text = []

for i in music:
  music_text.append(num_to_text[i])
print(''.join(music_text))# 길어서 리스트를 합침
# http://www.tradtunedb.org.uk/#/editor 에 값을 입력하면 음악이 나옴.

2"G"dB/2d/2"C"e/2d/2c/2B/2"D7"A/2G/2F/2A/2"G"G/2A/2B/2c/2"D7"d/2c/2B/2A/2"G"GB/2c/2dB"D"A/2F/2G/2A/2B/2A/2G/2F/2"D"D/2E/2F/2G/2"A7"A/2B/2A/2G/2"D"FD"A7"C/2F/2E/2D/2"D"FA"G"GB/2c/2"D"d/2c/2d/2e/2"G"dB/
