<a href="https://colab.research.google.com/github/Taeseong-eom/ApplePython/blob/main/%EC%9E%91%EA%B3%A1AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

with open('/content/drive/MyDrive/Colab Notebooks/pianoabc.txt','r') as file:
  text = file.read()
# 악보를 문자로 바꿀 수 있을까?
# abc notation 쓰면 된다.
# txt 파일은 악보를 txt로 바꿔놨다.

# 이제 문자를 숫자로 만들어서 학습시키자.
# 문자를 숫자로 바꾸는 방법
# 1. Bag of words(단어주머니) 만들어서 숫자로 변환
utext = list(set(text))
utext.sort()
# print(utext)

# 문자 -> 숫자 변환 딕셔너리
text_to_num = {}
num_to_text = {}
for i, data in enumerate(utext): # enumerate 로 변수 2개 사용
  text_to_num[data] = i
for i, data in enumerate(utext):
  num_to_text[i] = data

숫자화text=[]
for i in text:
  숫자화text.append(text_to_num[i])
# print(숫자화text)

# 그럼 이제 숫자화text를 가지고 trainX,Y를 만들어보자.

trainX, trainY = [], []

for i in range(0, len(숫자화text)-25):
    trainX.append(숫자화text[i:i+25])
    trainY.append(숫자화text[i+25])

import numpy as np
# 원핫인코딩할때 유니크한 문자가 많으면 부담된다.
# 그럴때 embedding layer를 사용한다.

# 원핫인코딩을 하자.
trainX = tf.one_hot(trainX, 31)
trainY = tf.one_hot(trainY, 31)
print(trainX[0:2])

tf.Tensor(
[[[0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]], shape=(2, 25, 31), dtype=float32)


In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(100, input_shape=(25,31)), # 노드수
    tf.keras.layers.Dense(31, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy']) # 원핫인코딩이 되어 있어서 sparse를 안붙여도 됨.
model.fit(trainX, trainY, batch_size=64, epochs=100, verbose=2) # batch_size=64 == 64번 할때마다 w 값 업데이트 // verbose=2 출력 값이 많으면 다운될 수 있어서 출력 많이 하지 말라 명령.
model.save('/content/drive/MyDrive/Colab Notebooks')

Epoch 1/100
4563/4563 - 134s - loss: 1.6126 - accuracy: 0.4932 - 134s/epoch - 29ms/step
Epoch 2/100
4563/4563 - 132s - loss: 1.2982 - accuracy: 0.5744 - 132s/epoch - 29ms/step
Epoch 3/100
4563/4563 - 130s - loss: 1.2009 - accuracy: 0.6048 - 130s/epoch - 29ms/step
Epoch 4/100
4563/4563 - 130s - loss: 1.1418 - accuracy: 0.6247 - 130s/epoch - 29ms/step
Epoch 5/100
4563/4563 - 129s - loss: 1.1031 - accuracy: 0.6369 - 129s/epoch - 28ms/step
Epoch 6/100
4563/4563 - 131s - loss: 1.0752 - accuracy: 0.6464 - 131s/epoch - 29ms/step
Epoch 7/100
4563/4563 - 130s - loss: 1.0515 - accuracy: 0.6536 - 130s/epoch - 29ms/step
Epoch 8/100
4563/4563 - 130s - loss: 1.0320 - accuracy: 0.6605 - 130s/epoch - 28ms/step
Epoch 9/100
4563/4563 - 130s - loss: 1.0152 - accuracy: 0.6660 - 130s/epoch - 28ms/step
Epoch 10/100
4563/4563 - 130s - loss: 1.0001 - accuracy: 0.6708 - 130s/epoch - 28ms/step
Epoch 11/100
4563/4563 - 130s - loss: 0.9864 - accuracy: 0.6751 - 130s/epoch - 28ms/step
Epoch 12/100
4563/4563 - 130s 